<a href="https://colab.research.google.com/github/MelisaAC/YPF-INGENIAS-DATA-SCIENCE-2024/blob/main/Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

In [4]:
#Crear un arreglo de ceros de longitud 12
array1=np.zeros(12)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
array2=np.zeros(10)
array2[4]=10
print(array2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [9]:
#Crear un arreglo que tenga los números del 10 al 49
array3=np.arange(10,50)
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
#Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array4=np.array (range(9)).reshape(3,3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
array5=np.random.randint(1,100,100)
print(array5)
media=np.mean(array5)
print(media)
varianza=np.var(array5)
print(varianza)

[40 60 66 49 82 79 86 49 64 37 33 48 91 44 37 62  7 69 47 10  3 15 79 72
 97 40 33 36  5 64 86 79 97 90 37  9 34 70 71 69 61 90  4 52 24 92 70  2
  9 89 26 70 77 50 51 63 13 53 38  7 51 40 37 77  6 96  4 75 57 88 30 22
 78  5 18 57 67 38 91 39 23 12 93 83 89 68  4 84 39 60 91 57 75 35 41 57
 38 75 10  4]
51.01
807.1498999999999


In [18]:
#Calcular la media de un arreglo usando np.sum
array5.sum()/array5.size

51.01

In [ ]:
#Calcular la varianza de un arreglo usando np.sum y np.mean


In [19]:
#Crear un array de números aleatorios usando np.random.randn
array6=np.random.randn (10)
print(array6)

[-0.49577959 -0.31797629 -0.01656275  0.67771429 -2.52946973  0.12244925
 -1.65046816 -0.65259683  1.10401745 -0.44954283]
